name: "Update Flakes"
on:
  schedule:
    # Run on the 1st and 15th of every month at 00:00 UTC
    - cron: "0 0 1,15 * *"
  workflow_dispatch:
jobs:
  update-flakes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Update flake inputs
        run: nix flake update
      - name: Check flake update
        run: nix flake check
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: nix flake update"
          title: "Update flake inputs"
          body: |
            Automated flake input updates.

            This PR was automatically created by the update-flakes workflow.

            **Auto-merge**: This PR will be automatically merged if all checks pass.
          branch: update-flakes
          delete-branch: true
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
      - name: Auto-merge Pull Request
        if: steps.cpr.outputs.pull-request-number != ''
        run: |
          gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --auto --squash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
